# Built with Jekyll 3.2.0
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:title:output_ext
color-scheme: red
# red, orange, green, cyan, blue, magenta, brown available
# Set encoding to UTF-8
encoding: utf-8

# Markdown specs
markdown: kramdown

collections:
  texts:
    output: true

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               hyunkim.lawyer
tagline:             'Musings of a simple lawyer on things other than the law'
description:         'Musings of a simple lawyer on things other than the law'
url:                 https://hyunkim.lawyer
baseurl:             ''

# About/contact
author:
  name:              Hyun Kim
  url:               https://hyunkim.lawyer
  email:             hyunkim@hyunkim.lawyer

# Custom vars
version:             0.0.5

# Exclude optional folder
exclude: [optional,unused]

# Gems
plugins: ['jekyll/scholar','jektex'] #,'jekyll-katex'

# Scholar
scholar:
  style: chicago-author-date-16th-edition
  locale: en
  allow_locale_overrides: true
  
  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/bibliography.html"

  replace_strings: true
  join_strings:    true

#  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

## defaults
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
